Set up env

In [1]:
import carla
import numpy as np
from src.simulator import Simulator
from src.agent import NCPAgent
from src.model import Model, Trainer

import torchvision
from IPython.display import display
import sys
import os
import torch
sys.path.append("CARLA_SIM/PythonAPI/carla/")
from agents.navigation.basic_agent import BasicAgent


In [2]:
simulator = Simulator(world_name='Town04_opt')

In [3]:
simulator.world.get_spectator().set_transform(
    carla.Transform(
        location=carla.Location(x=398.7934265136719,
                                y=-56.03200912475586,
                                z=3.37939715385437)))

simulator.spawn_car_with_camera(
    rel_coordinates=carla.Location(x=1.2, z=1.9) # camera coords
)
vehicle = simulator.get_vehicle()


output_size = 1
units = 19
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

ncp = Model(output_size, units)
ncp.to(device)

agent = NCPAgent(simulator, ncp, target_speed=10)

next_waypoint  = [simulator.world.get_map().get_waypoint(vehicle.get_location(),
                                                    project_to_road=True,
                                                    lane_type=(carla.LaneType.Driving))]

waypoints = []
dist_between_waypoints = 20
waypoint_num = 75
# waypoint_num = 10
for _ in range(waypoint_num):
    waypoints.append(next_waypoint[-1])
    # simulator.world.get_spectator().set_transform(next_waypoint[-1].transform)
    next_waypoint = next_waypoint[-1].next(dist_between_waypoints)

dest_idx = 2
dest = waypoints[dest_idx].transform.location
agent.set_destination(dest)
agent.set_target_speed(10)

cuda
alloc!
Camera stream started


In [4]:
# os.rmdir('./out/')

idx = 1
waypoint = waypoints[idx]
to_PIL = torchvision.transforms.ToPILImage()

loss_func = torch.nn.functional.mse_loss
optimizer = torch.optim.Adam(ncp.parameters(), lr=0.001)

# basic_agent = BasicAgent(vehicle=vehicle)
trainer = Trainer(ncp, loss_func, optimizer)

while True:
    # if vehicle.get_location().distance(dest) < 0.5:
    #     print(f"Destination reached")
    #     break
    # if (vehicle.get_location().distance(waypoint.transform.location) <= dist_between_waypoints / 4) or \
    #     (vehicle.get_location().distance(waypoint.transform.location) >= dist_between_waypoints * 2 and \
    #      vehicle.get_location().distance(waypoint.transform.location) <= dist_between_waypoints * 3):
    #     print(f'Waypoint {idx} was reached')
    #     waypoint = waypoints[idx + 1]
    #     idx += 1
    
    control, movement, raw_data, out_tensor = agent.run_step()
    trainer.train(raw_data, torch.tensor(control.steer))
    print(out_tensor)
    vehicle.apply_control(control)
    
    if agent.done():
        if dest_idx < waypoint_num - 1:
            dest_idx += 10
            dest_idx = min(dest_idx, waypoint_num - 1)
            print(f'Intermediate destination reached. Moving to waypoint {dest_idx}')
            agent.is_done = False
            agent.set_destination(waypoints[dest_idx].transform.location)
            continue

        print("The target has been reached, stopping the simulation")
        break
vehicle.apply_control(carla.VehicleControl(throttle = 0.0, brake=1.0, steer = 0.0))

/mnt/hard_drive/habkaffee_part/programming/coursework/src/model.py:76: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = self.loss_func(prediction, true_angle)


Current loss (*1000) = 2.02916, predicted = -0.0448237, true = 0.0002225
tensor([[-0.0364]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.25168, predicted = 0.0160876, true = 0.0002231
tensor([[0.0161]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.05269, predicted = 0.0074821, true = 0.0002234
tensor([[0.0075]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.03652, predicted = 0.0062672, true = 0.0002237
tensor([[0.0063]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.04292, predicted = 0.0067751, true = 0.0002240
tensor([[0.0068]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.04247, predicted = 0.0067412, true = 0.0002242
tensor([[0.0067]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.04017, predicted = 0.0065624, true = 0.0002245
tensor([[0.0066]], device='cuda:0', grad_fn=<SqueezeBackward1>)
Current loss (*1000) = 0.03223, predicted = 0.

In [ ]:
ncp.save_model(f'./model/pretrained_wp{waypoint_num}.pth')

In [ ]:
simulator.destroy_all()

# test

In [ ]:
ncp.load_state_dict(torch.load(f'model/pretrained_wp{waypoint_num}.pth'))

In [ ]:
print(ncp)

In [ ]:
ncp.eval()

In [ ]:
next_waypoint  = [simulator.world.get_map().get_waypoint(vehicle.get_location(),
                                                    project_to_road=True,
                                                    lane_type=(carla.LaneType.Driving))]

waypoints = []
dist_between_waypoints = 20
waypoint_num = 5
for _ in range(waypoint_num):
    waypoints.append(next_waypoint[-1])
    # simulator.world.get_spectator().set_transform(next_waypoint[-1].transform)
    next_waypoint = next_waypoint[-1].next(dist_between_waypoints)

dest_idx = 2
dest = waypoints[dest_idx].transform.location
agent.set_destination(dest)
agent.set_target_speed(10)

In [ ]:
idx = 1
waypoint = waypoints[idx]
to_PIL = torchvision.transforms.ToPILImage()

loss_func = torch.nn.functional.mse_loss
optimizer = torch.optim.Adam(ncp.parameters(), lr=0.001)

# basic_agent = BasicAgent(vehicle=vehicle)
# trainer = Trainer(ncp, loss_func, optimizer)

while True:
    # if vehicle.get_location().distance(dest) < 0.5:
    #     print(f"Destination reached")
    #     break
    # if (vehicle.get_location().distance(waypoint.transform.location) <= dist_between_waypoints / 4) or \
    #     (vehicle.get_location().distance(waypoint.transform.location) >= dist_between_waypoints * 2 and \
    #      vehicle.get_location().distance(waypoint.transform.location) <= dist_between_waypoints * 3):
    #     print(f'Waypoint {idx} was reached')
    #     waypoint = waypoints[idx + 1]
    #     idx += 1
    
    control, movement, raw_data, out_tensor = agent.run_step()
    # trainer.train(raw_data, torch.tensor(control.steer))
    print(control.steer, movement.item(), out_tensor)
    new_control = carla.VehicleControl(steer=movement.item(), throttle=control.throttle, brake=control.brake)
    vehicle.apply_control(new_control)
    
    if agent.done():
        if dest_idx < waypoint_num - 1:
            dest_idx += 10
            dest_idx = min(dest_idx, waypoint_num - 1)
            print(f'Intermediate destination reached. Moving to waypoint {dest_idx}')
            agent.is_done = False
            agent.set_destination(waypoints[dest_idx].transform.location)
            continue

        print("The target has been reached, stopping the simulation")
        break
vehicle.apply_control(carla.VehicleControl(throttle = 0.0, brake=1.0, steer = 0.0))

In [ ]:
simulator.destroy_all()

In [ ]:
# # we will save the conv layer weights in this list
# model_weights =[]
# #we will save the 49 conv layers in this list
# conv_layers = []
# # get all the model children as list
# model_children = list(model.children())
# #counter to keep count of the conv layers
# counter = 0
# #append all the conv layers and their respective wights to the list
# for i in range(len(model_children)):
#     if type(model_children[i]) == nn.Conv2d:
#         counter+=1
#         model_weights.append(model_children[i].weight)
#         conv_layers.append(model_children[i])
#     elif type(model_children[i]) == nn.Sequential:
#         for j in range(len(model_children[i])):
#             for child in model_children[i][j].children():
#                 if type(child) == nn.Conv2d:
#                     counter+=1
#                     model_weights.append(child.weight)
#                     conv_layers.append(child)
# print(f"Total convolution layers: {counter}")
# print(f"{conv_layers}")

In [ ]:
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# model = model.to(device)

In [ ]:
# image = transform(image)
# image = image[:3,:,:]
# print(f"Image shape before: {image.shape}")
# image = image.unsqueeze(0)
# print(f"Image shape after: {image.shape}")
# image = image.to(device)

In [ ]:
# outputs = []
# names = []
# for layer in conv_layers[0:]:
#     image = layer(image)
#     outputs.append(image)
#     names.append(str(layer))
# print(len(outputs))
# # print feature_maps
# for feature_map in outputs:
#     print(feature_map.shape)

In [ ]:
# processed = []
# for feature_map in outputs:
#     feature_map = feature_map.squeeze(0)
#     gray_scale = torch.sum(feature_map,0)
#     gray_scale = gray_scale / feature_map.shape[0]
#     processed.append(gray_scale.data.cpu().numpy())
# for fm in processed:
#     print(fm.shape)


In [ ]:
# fig = plt.figure(figsize=(30, 50))
# for i in range(len(processed)):
#     a = fig.add_subplot(5, 4, i+1)
#     imgplot = plt.imshow(processed[i])
#     a.axis("off")
#     a.set_title(names[i].split('(')[0], fontsize=30)
# plt.savefig(str('feature_maps.jpg'), bbox_inches='tight')


In [ ]:
# import torch
# import torch.nn as nn
# import pytorch_lightning as pl
# import torch.utils.data as data

# from src.model import SequenceLearner, NCP

# ncp = NCP(image_features.shape[1], output_size, units)
# ncp_model = ncp.get_ncp()
# learner = SequenceLearner(ncp_model, lr=0.01)
# trainer = pl.Trainer(
#     logger=pl.loggers.CSVLogger("log"),
#     max_epochs=5,
#     gradient_clip_val=1, #clip grad for training stabilizing
# )

Agent test

In [ ]:
import glob, os, sys
# sys.path.append(glob.glob('CARLA_SIM/PythonAPI/carla/'))
sys.path.append("CARLA_SIM/PythonAPI/carla/")
from agents.navigation.basic_agent import BasicAgent
# from agents.navigation.behavior_agent import BehaviorAgent

In [ ]:
simulator.spawn_car_with_camera()

In [ ]:
vehicle = simulator.get_vehicle()

In [ ]:
# agent = BehaviorAgent(vehicle, behavior='aggressive')
agent = BasicAgent(vehicle)
dest = simulator.spawn_points[50].location
agent.set_destination(dest)
agent.follow_speed_limits(False)
agent.set_target_speed(90)

In [ ]:
import time
while True:
    if agent.done():
        print("The target has been reached, stopping the simulation")
        break
    # if collided == True:
    #     vehicle.apply_control(carla.VehicleControl(throttle = 0.0, brake=1.0, steer = 0.0))
    #     print("Collision detected. Abort")
    #     break

    vehicle.apply_control(agent.run_step())
    # time.sleep(0.5)

In [ ]:
simulator.destroy_all()